---

site_name: GitOps Docs
site_description: My home Kubernetes (Kind) cluster managed by GitOps (Flux2)
site_author: Duy Henry
site_url: https://duyhenryer.github.io/gitops-docs/

repo_name: duyhenryer/gitops-docs
repo_url: https://github.com/duyhenryer/gitops-docs
edit_uri: "edit/master/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  # logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo

docs_dir: ./docs

extra_css:
- _static/custom.css

plugins:
- search

markdown_extensions:
- admonition
- meta
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.superfences:
    highlight_code: true
- pymdownx.snippets
- pymdownx.tabbed
- pymdownx.tilde
- pymdownx.progressbar
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Introduction: index.md
- External Secrets: external-secrets.md
- Flux: flux.md
- Opnsense:
  - BGP: opnsense/bgp.md
  - PXE: opnsense/pxe.md
- Rook-Ceph Maintenance: rook-ceph-maintenance.md
- Sealed Secrets: sealed-secrets.md
- Snmp Exporter: snmp-exporter.md
- Velero: velero.md
- HelmRelease: helmrelease.md
- AWS:
  - EC2: aws/ec2.md
  - EKS: aws/eks.md
- Monitoring-Logging:
- Docker:
- Kubernetes:
  - deployment: k8s/deployment.md
  - service: k8s/service.md
- Helm:
