---

site_name: Docs
site_description: My docs.
site_author: Duy Henry
site_url: https://duyhenryer.github.io/docs/

repo_name: duyhenryer/gitops-docs
repo_url: https://github.com/duyhenryer/docs
edit_uri: "edit/master/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  # logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo

docs_dir: ./docs

extra_css:
- _static/custom.css

plugins:
- search

markdown_extensions:
- admonition
- meta
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.superfences:
    highlight_code: true
- pymdownx.snippets
- pymdownx.tabbed
- pymdownx.tilde
- pymdownx.progressbar
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Introduction: index.md
- Flux: flux.md
- HelmRelease: helmrelease.md
- AWS:
  - ec2: aws/ec2.md
  - eks: aws/eks.md
- GCP:
  - vm: gcp/vps.md
- GitOps:
  - Fluxcd: gitops/fluxcd.md
  - Argo: gitops/argo.md
- Docker:
  - volume: docker/volume.md
  - volume: docker/logging.md
- Kubernetes:
  - deployment: k8s/deployment.md
  - service: k8s/service.md
  - networking: k8s/networking.md
- Helm:
  - Tips: helm/tips.md
- Networking:
  - Iptables: networking/iptables.md
- Databases:
  - MySQL: databases/mysql.md
  - MongoDB: databases/mongodb.md
  - PostgreSQL: databases/postgresql.md
- Kafka:
  - Debezium: kafka/Debezium.md
  - CheatSheet: kafka/cheat-sheet.md
  - Kafka: kafka/kafka.md
- Cache:
  - Redis: cache/redis.md
- Linux:
  - Tips: linux/tips.md
  - Curl: linux/curl.md
- Github: git.md